#######################################
##      IpLock Configuration         ##
#######################################

# whether names should be checked to be frem the same subnet as before if ip is different
checkSubnet: true

# block users if name is not alphanumerical?
blockSpecialChars: true

# max username length allowed to login (0 to disable)
max_namelen: 20

# will hold a temp. user cache in plugin, to lower resource usage during a login
#   use this to change how long it is considered current (seconds)
tempCacheTTL: 10

# what to use for tablename/filename
tableName: iplockusers

# use mysql?
useMySQLUserDB: false

MySQL:
    # database to use in MySQL
    database: minecraft
    # MySQL Login Username
    username: root
    # MySQL Login Password
    password: root
    # MySQL Connection Hostname (IP)
    Hostname: localhost
    # MySQL Connection Port Number
    Port: 3306
    
# whether certain names get special treatment
# include - only check the listed names
# exclude - don't check the listed names
# none (default) - everyone is checked
checkOption: none
# list of users to apply the above rule to (space or comma-delimited)
users:


# option to not kick, but to freeze users until they insert a password to unlock their ip
passwordUpdate: false
# new users require a password to start?
passwordLock: false
# what a user needs to enter to unlock or start (caSe-SensiTive)
defaultPass: password
# how long before auto-kick (0 for disabled)
#   positive integer values only, units being s(econds) m(inutes) (default: s)
passTimeout: 30s
# tries before locked out
maxAttempts: 3
# time before allowed to try again (saved in memory, lost on server restart)
#   positive integer values only, units being s(econds) m(inutes) h(hours) d(ays) w(eeks) M(onths) (default: m)
retryTime: 1h