name: iplock
main: net.gamerservices.iplock.iplock
version: 0.024
author: mixxit
website: http://www.gamerservices.net
description: >
    prevents users from logging in from multiple ip addresses (two boxing prevention)
commands:
   iplock:
    description: General command for interacting with iplock
    usage: /<command> reload | reset <user>
    aliases: [ipl]