name: iplock
main: me.jascotty2.iplock.IPLock
version: 1.2.1
author: jascotty2
website: https://github.com/jascotty2/iplock
description: >
    prevents users from logging in from multiple ip addresses (two boxing prevention)
commands:
    iplock:
        description: General command for interacting with iplock
        usage: /<command> reload | reset <user>
        aliases: [ipl]
    passwd:
        description: password to unlock & change your ip
        usage: /<command> <password>
        aliases: [password, pass, p]
   